# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8e1b46ba051ce2dbaa7244090edd00b264ec355248577bb126d9076711e89b01d73b90b168b9ec5375ace676e22c3adc36dfb10f2a71fcb1826783ae02dda70a

test:
  secret_key_base: ef04a0e1c150c99d6563933e6529e304ca8d66e44cf4111ba8578850f2ef0a6c28cc8667a6c3008b5f319d1bf59fc8137da155514f6e72a662b5c9bee239c3ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
